# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/addRomFile.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_rom_file_dialog(object):
    def setupUi(self, add_rom_file_dialog):
        add_rom_file_dialog.setObjectName("add_rom_file_dialog")
        add_rom_file_dialog.resize(735, 219)
        self.gridLayout = QtWidgets.QGridLayout(add_rom_file_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.rom_add_hash_button_box = QtWidgets.QDialogButtonBox(add_rom_file_dialog)
        self.rom_add_hash_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.rom_add_hash_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.rom_add_hash_button_box.setObjectName("rom_add_hash_button_box")
        self.gridLayout.addWidget(self.rom_add_hash_button_box, 4, 0, 1, 1)
        self.add_roms_label = QtWidgets.QLabel(add_rom_file_dialog)
        self.add_roms_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.add_roms_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_roms_label.setAlignment(QtCore.Qt.AlignCenter)
        self.add_roms_label.setObjectName("add_roms_label")
        self.gridLayout.addWidget(self.add_roms_label, 0, 0, 1, 2)
        self.console_layout = QtWidgets.QHBoxLayout()
        self.console_layout.setSpacing(10)
        self.console_layout.setObjectName("console_layout")
        self.console_name_label = QtWidgets.QLabel(add_rom_file_dialog)
        self.console_name_label.setMinimumSize(QtCore.QSize(150, 35))
        self.console_name_label.setMaximumSize(QtCore.QSize(150, 35))
        self.console_name_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.console_name_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.console_name_label.setObjectName("console_name_label")
        self.console_layout.addWidget(self.console_name_label)
        self.console_name_combo = QtWidgets.QComboBox(add_rom_file_dialog)
        self.console_name_combo.setMinimumSize(QtCore.QSize(0, 35))
        self.console_name_combo.setMaximumSize(QtCore.QSize(16777215, 35))
        self.console_name_combo.setObjectName("console_name_combo")
        self.console_layout.addWidget(self.console_name_combo)
        self.gridLayout.addLayout(self.console_layout, 1, 0, 1, 1)
        self.file_layout = QtWidgets.QHBoxLayout()
        self.file_layout.setObjectName("file_layout")
        self.file_label = QtWidgets.QLabel(add_rom_file_dialog)
        self.file_label.setMinimumSize(QtCore.QSize(150, 35))
        self.file_label.setMaximumSize(QtCore.QSize(150, 35))
        self.file_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.file_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_label.setObjectName("file_label")
        self.file_layout.addWidget(self.file_label)
        self.file_line_edit = QtWidgets.QLineEdit(add_rom_file_dialog)
        self.file_line_edit.setObjectName("file_line_edit")
        self.file_layout.addWidget(self.file_line_edit)
        self.file_button = QtWidgets.QPushButton(add_rom_file_dialog)
        self.file_button.setObjectName("file_button")
        self.file_layout.addWidget(self.file_button)
        self.gridLayout.addLayout(self.file_layout, 2, 0, 1, 1)
        self.verify_layout = QtWidgets.QHBoxLayout()
        self.verify_layout.setObjectName("verify_layout")
        self.verify_label = QtWidgets.QLabel(add_rom_file_dialog)
        self.verify_label.setMinimumSize(QtCore.QSize(150, 35))
        self.verify_label.setMaximumSize(QtCore.QSize(150, 35))
        self.verify_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.verify_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verify_label.setObjectName("verify_label")
        self.verify_layout.addWidget(self.verify_label)
        self.verify_line_edit = QtWidgets.QLineEdit(add_rom_file_dialog)
        self.verify_line_edit.setObjectName("verify_line_edit")
        self.verify_layout.addWidget(self.verify_line_edit)
        self.verify_button = QtWidgets.QPushButton(add_rom_file_dialog)
        self.verify_button.setObjectName("verify_button")
        self.verify_layout.addWidget(self.verify_button)
        self.gridLayout.addLayout(self.verify_layout, 3, 0, 1, 1)

        self.retranslateUi(add_rom_file_dialog)
        self.rom_add_hash_button_box.accepted.connect(add_rom_file_dialog.accept)
        self.rom_add_hash_button_box.rejected.connect(add_rom_file_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(add_rom_file_dialog)

    def retranslateUi(self, add_rom_file_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_rom_file_dialog.setWindowTitle(_translate("add_rom_file_dialog", "Dialog"))
        self.add_roms_label.setText(_translate("add_rom_file_dialog", "Add Roms from file. XML or -listfull and -verify outputs (MAME)."))
        self.console_name_label.setText(_translate("add_rom_file_dialog", "Console Name: "))
        self.file_label.setText(_translate("add_rom_file_dialog", "File To Read:"))
        self.file_button.setText(_translate("add_rom_file_dialog", "Open"))
        self.verify_label.setText(_translate("add_rom_file_dialog", "Verify File:"))
        self.verify_button.setText(_translate("add_rom_file_dialog", "Open"))

