# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/addRomDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_rom_dialog(object):
    def setupUi(self, add_rom_dialog):
        add_rom_dialog.setObjectName("add_rom_dialog")
        add_rom_dialog.resize(1108, 374)
        self.gridLayout = QtWidgets.QGridLayout(add_rom_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.description_label = QtWidgets.QLabel(add_rom_dialog)
        self.description_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.description_label.setAlignment(QtCore.Qt.AlignCenter)
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 0, 0, 1, 1)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSpacing(5)
        self.main_layout.setObjectName("main_layout")
        self.console_layout = QtWidgets.QHBoxLayout()
        self.console_layout.setSpacing(10)
        self.console_layout.setObjectName("console_layout")
        self.console_name_label = QtWidgets.QLabel(add_rom_dialog)
        self.console_name_label.setMinimumSize(QtCore.QSize(150, 35))
        self.console_name_label.setMaximumSize(QtCore.QSize(150, 35))
        self.console_name_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.console_name_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.console_name_label.setObjectName("console_name_label")
        self.console_layout.addWidget(self.console_name_label)
        self.console_name_combo = QtWidgets.QComboBox(add_rom_dialog)
        self.console_name_combo.setMinimumSize(QtCore.QSize(0, 35))
        self.console_name_combo.setMaximumSize(QtCore.QSize(16777215, 35))
        self.console_name_combo.setObjectName("console_name_combo")
        self.console_layout.addWidget(self.console_name_combo)
        self.main_layout.addLayout(self.console_layout)
        self.hash_layout = QtWidgets.QHBoxLayout()
        self.hash_layout.setObjectName("hash_layout")
        self.hash_checkbox = QtWidgets.QCheckBox(add_rom_dialog)
        self.hash_checkbox.setMinimumSize(QtCore.QSize(200, 35))
        self.hash_checkbox.setMaximumSize(QtCore.QSize(200, 35))
        self.hash_checkbox.setObjectName("hash_checkbox")
        self.hash_layout.addWidget(self.hash_checkbox)
        self.hash_line_edit = QtWidgets.QLineEdit(add_rom_dialog)
        self.hash_line_edit.setObjectName("hash_line_edit")
        self.hash_layout.addWidget(self.hash_line_edit)
        self.hash_button = QtWidgets.QPushButton(add_rom_dialog)
        self.hash_button.setObjectName("hash_button")
        self.hash_layout.addWidget(self.hash_button)
        self.main_layout.addLayout(self.hash_layout)
        self.listfull_layout = QtWidgets.QHBoxLayout()
        self.listfull_layout.setObjectName("listfull_layout")
        self.listfull_checkbox = QtWidgets.QCheckBox(add_rom_dialog)
        self.listfull_checkbox.setMinimumSize(QtCore.QSize(200, 35))
        self.listfull_checkbox.setMaximumSize(QtCore.QSize(200, 35))
        self.listfull_checkbox.setObjectName("listfull_checkbox")
        self.listfull_layout.addWidget(self.listfull_checkbox)
        self.listfull_line_edit = QtWidgets.QLineEdit(add_rom_dialog)
        self.listfull_line_edit.setObjectName("listfull_line_edit")
        self.listfull_layout.addWidget(self.listfull_line_edit)
        self.listfull_button = QtWidgets.QPushButton(add_rom_dialog)
        self.listfull_button.setObjectName("listfull_button")
        self.listfull_layout.addWidget(self.listfull_button)
        self.main_layout.addLayout(self.listfull_layout)
        self.verify_layout = QtWidgets.QHBoxLayout()
        self.verify_layout.setObjectName("verify_layout")
        self.verify_checkbox = QtWidgets.QCheckBox(add_rom_dialog)
        self.verify_checkbox.setMinimumSize(QtCore.QSize(200, 35))
        self.verify_checkbox.setMaximumSize(QtCore.QSize(200, 35))
        self.verify_checkbox.setObjectName("verify_checkbox")
        self.verify_layout.addWidget(self.verify_checkbox)
        self.verify_line_edit = QtWidgets.QLineEdit(add_rom_dialog)
        self.verify_line_edit.setObjectName("verify_line_edit")
        self.verify_layout.addWidget(self.verify_line_edit)
        self.verify_button = QtWidgets.QPushButton(add_rom_dialog)
        self.verify_button.setObjectName("verify_button")
        self.verify_layout.addWidget(self.verify_button)
        self.main_layout.addLayout(self.verify_layout)
        self.custom_layout = QtWidgets.QHBoxLayout()
        self.custom_layout.setObjectName("custom_layout")
        self.custom_checkbox = QtWidgets.QCheckBox(add_rom_dialog)
        self.custom_checkbox.setMinimumSize(QtCore.QSize(200, 35))
        self.custom_checkbox.setMaximumSize(QtCore.QSize(200, 35))
        self.custom_checkbox.setObjectName("custom_checkbox")
        self.custom_layout.addWidget(self.custom_checkbox)
        self.custom_line_edit = QtWidgets.QLineEdit(add_rom_dialog)
        self.custom_line_edit.setObjectName("custom_line_edit")
        self.custom_layout.addWidget(self.custom_line_edit)
        self.custom_button = QtWidgets.QPushButton(add_rom_dialog)
        self.custom_button.setObjectName("custom_button")
        self.custom_layout.addWidget(self.custom_button)
        self.main_layout.addLayout(self.custom_layout)
        self.directory_layout = QtWidgets.QHBoxLayout()
        self.directory_layout.setSpacing(10)
        self.directory_layout.setObjectName("directory_layout")
        self.directory_checkbox = QtWidgets.QCheckBox(add_rom_dialog)
        self.directory_checkbox.setMinimumSize(QtCore.QSize(200, 35))
        self.directory_checkbox.setMaximumSize(QtCore.QSize(200, 35))
        self.directory_checkbox.setObjectName("directory_checkbox")
        self.directory_layout.addWidget(self.directory_checkbox)
        self.directory_line_edit = QtWidgets.QLineEdit(add_rom_dialog)
        self.directory_line_edit.setInputMask("")
        self.directory_line_edit.setObjectName("directory_line_edit")
        self.directory_layout.addWidget(self.directory_line_edit)
        self.directory_button = QtWidgets.QPushButton(add_rom_dialog)
        self.directory_button.setObjectName("directory_button")
        self.directory_layout.addWidget(self.directory_button)
        self.main_layout.addLayout(self.directory_layout)
        self.extension_layout = QtWidgets.QHBoxLayout()
        self.extension_layout.setSpacing(10)
        self.extension_layout.setObjectName("extension_layout")
        self.extension_checkbox = QtWidgets.QCheckBox(add_rom_dialog)
        self.extension_checkbox.setMinimumSize(QtCore.QSize(200, 35))
        self.extension_checkbox.setMaximumSize(QtCore.QSize(200, 35))
        self.extension_checkbox.setObjectName("extension_checkbox")
        self.extension_layout.addWidget(self.extension_checkbox)
        self.extension_line_edit = QtWidgets.QLineEdit(add_rom_dialog)
        self.extension_line_edit.setObjectName("extension_line_edit")
        self.extension_layout.addWidget(self.extension_line_edit)
        self.main_layout.addLayout(self.extension_layout)
        self.gridLayout.addLayout(self.main_layout, 1, 0, 1, 1)
        self.rom_add_button_box = QtWidgets.QDialogButtonBox(add_rom_dialog)
        self.rom_add_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.rom_add_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.rom_add_button_box.setObjectName("rom_add_button_box")
        self.gridLayout.addWidget(self.rom_add_button_box, 3, 0, 1, 1)
        self.add_roms_progress = QtWidgets.QProgressBar(add_rom_dialog)
        self.add_roms_progress.setProperty("value", 0)
        self.add_roms_progress.setObjectName("add_roms_progress")
        self.gridLayout.addWidget(self.add_roms_progress, 4, 0, 1, 1)

        self.retranslateUi(add_rom_dialog)
        self.rom_add_button_box.accepted.connect(add_rom_dialog.accept)
        self.rom_add_button_box.rejected.connect(add_rom_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(add_rom_dialog)

    def retranslateUi(self, add_rom_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_rom_dialog.setWindowTitle(_translate("add_rom_dialog", "Add Roms From Directory"))
        self.description_label.setText(_translate("add_rom_dialog", "Add roms based on choices below. Some are required together (Directory and Extension)"))
        self.console_name_label.setText(_translate("add_rom_dialog", "Console Name: "))
        self.hash_checkbox.setText(_translate("add_rom_dialog", "Softlist Hash:"))
        self.hash_button.setText(_translate("add_rom_dialog", "Open"))
        self.listfull_checkbox.setText(_translate("add_rom_dialog", "MAME -listfull:"))
        self.listfull_button.setText(_translate("add_rom_dialog", "Open"))
        self.verify_checkbox.setText(_translate("add_rom_dialog", "MAME -verify:"))
        self.verify_button.setText(_translate("add_rom_dialog", "Open"))
        self.custom_checkbox.setText(_translate("add_rom_dialog", "MAME Custom List:"))
        self.custom_button.setText(_translate("add_rom_dialog", "Open"))
        self.directory_checkbox.setText(_translate("add_rom_dialog", "Directory:"))
        self.directory_button.setText(_translate("add_rom_dialog", "Open"))
        self.extension_checkbox.setText(_translate("add_rom_dialog", "Extension:"))

