# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/emuMenuMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_emumenu_main_window(object):
    def setupUi(self, emumenu_main_window):
        emumenu_main_window.setObjectName("emumenu_main_window")
        emumenu_main_window.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(emumenu_main_window.sizePolicy().hasHeightForWidth())
        emumenu_main_window.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("main")
        emumenu_main_window.setWindowIcon(icon)
        emumenu_main_window.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.main_grid = QtWidgets.QWidget(emumenu_main_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.main_grid.sizePolicy().hasHeightForWidth())
        self.main_grid.setSizePolicy(sizePolicy)
        self.main_grid.setObjectName("main_grid")
        self.gridLayout = QtWidgets.QGridLayout(self.main_grid)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.child_grid = QtWidgets.QGridLayout()
        self.child_grid.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.child_grid.setHorizontalSpacing(5)
        self.child_grid.setVerticalSpacing(0)
        self.child_grid.setObjectName("child_grid")
        self.rom_layout = QtWidgets.QVBoxLayout()
        self.rom_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.rom_layout.setSpacing(2)
        self.rom_layout.setObjectName("rom_layout")
        self.rom_label = QtWidgets.QLabel(self.main_grid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rom_label.sizePolicy().hasHeightForWidth())
        self.rom_label.setSizePolicy(sizePolicy)
        self.rom_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.rom_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.rom_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rom_label.setScaledContents(True)
        self.rom_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rom_label.setObjectName("rom_label")
        self.rom_layout.addWidget(self.rom_label)
        self.rom_scroll_area = QtWidgets.QScrollArea(self.main_grid)
        self.rom_scroll_area.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rom_scroll_area.setAutoFillBackground(True)
        self.rom_scroll_area.setWidgetResizable(True)
        self.rom_scroll_area.setObjectName("rom_scroll_area")
        self.rom_scroll_area_layout = QtWidgets.QWidget()
        self.rom_scroll_area_layout.setGeometry(QtCore.QRect(0, 0, 383, 456))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rom_scroll_area_layout.sizePolicy().hasHeightForWidth())
        self.rom_scroll_area_layout.setSizePolicy(sizePolicy)
        self.rom_scroll_area_layout.setObjectName("rom_scroll_area_layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rom_scroll_area_layout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rom_list_widget = QtWidgets.QListWidget(self.rom_scroll_area_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rom_list_widget.sizePolicy().hasHeightForWidth())
        self.rom_list_widget.setSizePolicy(sizePolicy)
        self.rom_list_widget.setAutoFillBackground(True)
        self.rom_list_widget.setObjectName("rom_list_widget")
        self.verticalLayout_2.addWidget(self.rom_list_widget)
        self.rom_scroll_area.setWidget(self.rom_scroll_area_layout)
        self.rom_layout.addWidget(self.rom_scroll_area)
        self.child_grid.addLayout(self.rom_layout, 0, 1, 1, 1)
        self.console_layout = QtWidgets.QVBoxLayout()
        self.console_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.console_layout.setSpacing(2)
        self.console_layout.setObjectName("console_layout")
        self.console_label = QtWidgets.QLabel(self.main_grid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_label.sizePolicy().hasHeightForWidth())
        self.console_label.setSizePolicy(sizePolicy)
        self.console_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.console_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.console_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.console_label.setScaledContents(True)
        self.console_label.setAlignment(QtCore.Qt.AlignCenter)
        self.console_label.setObjectName("console_label")
        self.console_layout.addWidget(self.console_label)
        self.console_scroll_area = QtWidgets.QScrollArea(self.main_grid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_scroll_area.sizePolicy().hasHeightForWidth())
        self.console_scroll_area.setSizePolicy(sizePolicy)
        self.console_scroll_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.console_scroll_area.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.console_scroll_area.setAutoFillBackground(True)
        self.console_scroll_area.setWidgetResizable(True)
        self.console_scroll_area.setObjectName("console_scroll_area")
        self.console_scroll_area_layout = QtWidgets.QWidget()
        self.console_scroll_area_layout.setGeometry(QtCore.QRect(0, 0, 384, 456))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_scroll_area_layout.sizePolicy().hasHeightForWidth())
        self.console_scroll_area_layout.setSizePolicy(sizePolicy)
        self.console_scroll_area_layout.setObjectName("console_scroll_area_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.console_scroll_area_layout)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.console_list_widget = QtWidgets.QListWidget(self.console_scroll_area_layout)
        self.console_list_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.console_list_widget.setResizeMode(QtWidgets.QListView.Adjust)
        self.console_list_widget.setObjectName("console_list_widget")
        self.verticalLayout.addWidget(self.console_list_widget)
        self.console_scroll_area.setWidget(self.console_scroll_area_layout)
        self.console_layout.addWidget(self.console_scroll_area)
        self.child_grid.addLayout(self.console_layout, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.child_grid, 0, 0, 1, 1)
        self.status_bar = QtWidgets.QStatusBar(self.main_grid)
        self.status_bar.setObjectName("status_bar")
        self.gridLayout.addWidget(self.status_bar, 2, 0, 1, 1)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.favorites_button = QtWidgets.QPushButton(self.main_grid)
        self.favorites_button.setObjectName("favorites_button")
        self.button_layout.addWidget(self.favorites_button)
        self.search_button = QtWidgets.QPushButton(self.main_grid)
        self.search_button.setObjectName("search_button")
        self.button_layout.addWidget(self.search_button)
        self.random_button = QtWidgets.QPushButton(self.main_grid)
        self.random_button.setObjectName("random_button")
        self.button_layout.addWidget(self.random_button)
        self.gridLayout.addLayout(self.button_layout, 1, 0, 1, 1)
        emumenu_main_window.setCentralWidget(self.main_grid)
        self.emumenu_menu = QtWidgets.QMenuBar(emumenu_main_window)
        self.emumenu_menu.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.emumenu_menu.setObjectName("emumenu_menu")
        self.menu_menu = QtWidgets.QMenu(self.emumenu_menu)
        self.menu_menu.setObjectName("menu_menu")
        emumenu_main_window.setMenuBar(self.emumenu_menu)
        self.action_add_console = QtWidgets.QAction(emumenu_main_window)
        self.action_add_console.setObjectName("action_add_console")
        self.action_add_roms = QtWidgets.QAction(emumenu_main_window)
        self.action_add_roms.setObjectName("action_add_roms")
        self.action_quit = QtWidgets.QAction(emumenu_main_window)
        self.action_quit.setObjectName("action_quit")
        self.action_edit_console_command = QtWidgets.QAction(emumenu_main_window)
        self.action_edit_console_command.setObjectName("action_edit_console_command")
        self.menu_menu.addAction(self.action_add_console)
        self.menu_menu.addAction(self.action_add_roms)
        self.menu_menu.addAction(self.action_edit_console_command)
        self.menu_menu.addSeparator()
        self.menu_menu.addAction(self.action_quit)
        self.emumenu_menu.addAction(self.menu_menu.menuAction())

        self.retranslateUi(emumenu_main_window)
        QtCore.QMetaObject.connectSlotsByName(emumenu_main_window)

    def retranslateUi(self, emumenu_main_window):
        _translate = QtCore.QCoreApplication.translate
        emumenu_main_window.setWindowTitle(_translate("emumenu_main_window", "emuMenu"))
        self.rom_label.setText(_translate("emumenu_main_window", "Game"))
        self.console_label.setText(_translate("emumenu_main_window", "Console"))
        self.favorites_button.setText(_translate("emumenu_main_window", "Favorites"))
        self.search_button.setText(_translate("emumenu_main_window", "Search"))
        self.random_button.setText(_translate("emumenu_main_window", "Play Random Game"))
        self.menu_menu.setTitle(_translate("emumenu_main_window", "&Menu"))
        self.action_add_console.setText(_translate("emumenu_main_window", "&Add Console"))
        self.action_add_roms.setText(_translate("emumenu_main_window", "Add &Roms"))
        self.action_quit.setText(_translate("emumenu_main_window", "&Quit"))
        self.action_edit_console_command.setText(_translate("emumenu_main_window", "&Edit Console Command"))

